language: node_js
node_js:
  - 13

branches:
  only:
    - master
  except:
    - develop

git:
  strategy: clone
  depth: 1

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t flowmar/feed-module:latest ./feed/
  - docker build -t flowmar/user-module:latest ./user/
  - docker build -t flowmar/micro-frontend:latest ./frontend/

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push flowmar/feed-module
  - docker push flowmar/user-module
  - docker push flowmar/micro-frontend
